linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 10
  gomoddirectives:
    replace-local: false
    replace-allow-list:
      - github.com/go-git/go-git/v5
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 4
    ignore-tests: true
  lll:
    line-length: 140
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - fatcontext
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    ## - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tenv
    ## - testifylint
    ## - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wsl
    # slower linters
    - gosimple
    - staticcheck
    - stylecheck

run:
  concurrency: 8
  timeout: 10m
