version: "2"

run:
  concurrency: 8

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    ## - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    ## - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wsl

  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 4
    gocyclo:
      min-complexity: 10
    gomoddirectives:
      replace-local: false
    govet:
      enable-all: true
    lll:
      line-length: 140
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
